platform :ios, '8.0'

use_frameworks!

target "Packager" do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
  ]
end

target "Demo" do
  pod 'Xealth', :path => '../Xealth.podspec'
end